version: "3"

services:
  node:
    build: .
    container_name: store_manager
    tty: true
    stdin_open: true
    command: bash
    restart: always
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    depends_on:
      - db
    ports:
      - 3000:3000 # API port
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: '12345678' # mysql password for container
      MYSQL_HOST: db
      PORT: '3000' # API port

  db:
    container_name: store_manager_db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: '12345678' # mysql password for container
    ports:
      - 3306:3306 # mysql container port

networks:
  default:
    name: store_manager_net

volumes:
  node_modules:
